version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "vanhoof"  # Replace with your GitHub username
    assignees:
      - "vanhoof"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      include: "scope"