name: PR Checks

on:
  pull_request:
    branches: [ main, main-next ]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: PR Title Check
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          ci
          chore
        requireScope: false
    
    - name: Label PR
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
    
    - name: Check for conflicts
      uses: eps1lon/actions-label-merge-conflict@v2
      with:
        dirtyLabel: "conflicts"
        repoToken: ${{ secrets.GITHUB_TOKEN }}